### 1. GET all posts
GET http://localhost:8000/posts

###

### 2. POST (Create a new post)
POST http://localhost:8000/posts
Content-Type: application/json

{
  "title": "My New Post",
  "body": "This is a brand new post.",
  "tags": [
        "history",
        "american",
        "crime"
      ],
      "reactions": {
        "likes": 192,
        "dislikes": 25
      },
      "views": 305,
  "userId": 1
}

###
### 3. PUT (Update entire post)
PUT http://localhost:8000/posts/2
Content-Type: application/json

{
  "title": "Completely Updated Title",
  "body": "Completely updated body text.",
  "userId": 1
}

###
### 4. PATCH (Update single field)
PATCH http://localhost:8000/posts/1
Content-Type: application/json

{
  "title": "Only Updated Title"
}

###
### 5. DELETE a post
DELETE http://localhost:8000/posts/1

###

### 1. GET all posts
GET http://localhost:3000/posts

###

### 2. POST (Create a new post)
POST http://localhost:3000/posts
Content-Type: application/json

{"title": "My New Post", "body": "This is a brand new post.", "tags": ["history", "american", "crime"], "reactions": {"likes": 192, "dislikes": 25}, "views": 305, "userId": 1}

###

### 3. PUT (Update entire post)
PUT http://localhost:3000/posts/2
Content-Type: application/json

{"title": "Completely Updated Title", "body": "Completely updated body text.", "userId": 1}

###

### 4. PATCH (Update single field)
PATCH http://localhost:3000/posts/1
Content-Type: application/json

{"title": "Only Updated Title"}

###

### 5. DELETE a post
DELETE http://localhost:3000/posts/1